spring.application.name=ViagensBackEnd

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.fail-on-empty-beans=false

server.error.include-message=always
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/viagens
spring.datasource.username=postgres
spring.datasource.password=2770
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=changeitchangeitchangeitchangeit
security.jwt.expiration-seconds=28800