spring.application.name=ViagensBackEnd
spring.jpa.show-sql=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.hibernate.ddl-auto=none
server.error.include-message=always

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:viagensbackend;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driver-class-name=org.h2.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:/

security.jwt.secret=${SECURITY_JWT_SECRET:changeitchangeitchangeitchangeit}